pipeline {
    agent { label 'node' }
    options {
        timeout(time: 45, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    environment {
        OC_PROJECT = 'prefect'
        BASE_IMG_NAME = 'prefecthq/prefect'
        OC_URL = 'https://c113-e.private.eu-de.containers.cloud.ibm.com:30227'
        JIRA_URL = 'meemoo.atlassian.net'
        APP_NAME = 'prefect-meemoo'
        PREFECT_QUEUE= 'q-test'
        REGISTRY = 'default-route-openshift-image-registry.meemoo2-2bc857e5f10eb63ab790a3a1d19a696c-i000.eu-de.containers.appdomain.cloud'
        REGISTRY_SCHEMA = "https://$REGISTRY"
        REGISTRY_CREDENTIAL = 'docker-reg'
        PIP_ARGS="--extra-index-url http://do-prd-mvn-01.do.viaa.be:8081/repository/pypi-all/simple --trusted-host do-prd-mvn-01.do.viaa.be"
        PYPI_URL="http://do-prd-mvn-01.do.viaa.be:8081/repository/pypi-internal/"
    }

    stages {
        stage('Calculate extra ENV vars') {
            steps {
                script {
                    env.GIT_SHORT_COMMIT = sh(script: "printf \$(git rev-parse --short ${GIT_COMMIT})", returnStdout: true)
                    env.GIT_TAG = sh(script: 'git tag | tail -1', returnStdout: true)
                    env.IMAGE_TAG = sh(script: 'git describe --tags || echo latest', returnStdout: true)
                    // The name used for the build config based on the image tag
                    // Replace '.' with '_' as '.' is not allowed.
                    env.BUILD_CONFIG_NAME = sh(script: 'echo "${IMAGE_TAG}" | tr -d \'\\n\' | sed -r "s/\\-//g"', returnStdout: true)
                    env.DOCKER_IMAGE = sh(script: 'echo "${APP_NAME}:${GIT_SHORT_COMMIT}"')
                }
            }
        }
        stage('Calculate INT ENV variables') {
            when {
                anyOf {
                    changeRequest target: 'master'
                    changeRequest target: 'main'
                    allOf {
                        buildingTag()
                        expression {
                            return env.BUILD_CONFIG_NAME.contains('a')
                        }
                    }
                }
            }
            steps {
                script {
                    getPrefectApiAndVersion('int')
                }
            }
            post {
                always {
                    script {
                        env.BRANCH_NAME = env.CHANGE_BRANCH
                    }
                    jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'int', environmentName: 'int', environmentType: 'testing'
                }
            }
        }
        stage('Calculate QAS ENV variables') {
            when {
                anyOf { 
                    branch 'master'
                    branch 'main'
                    allOf {
                        buildingTag()
                        expression {
                            return env.BUILD_CONFIG_NAME.contains('b')
                        }
                    }
                }
            }
            steps {
                script {
                    getPrefectApiAndVersion('qas')
                }
            }
            post {
                always {
                    jiraSendDeploymentInfo site: "${JIRA_URL}", environmentId: 'qas', environmentName: 'qas', environmentType: 'staging'
                }
             }
        }
        stage('Calculate PRD ENV variables') {
            when {
                allOf{
                    buildingTag()
                    not {
                        expression {
                            return env.BUILD_CONFIG_NAME.contains('a') || env.BUILD_CONFIG_NAME.contains('b')
                        }
                    }
                }
            }
            steps {
                script {
                    getPrefectApiAndVersion('prd')
                }
            }
        }
        stage('Build image') {
            steps {
                script {
                    // The jenkins docker plugin doesn't provide the `--build-arg` option
                    sh "docker build . -t prefect-meemoo:$GIT_SHORT_COMMIT --build-arg PIP_ARGS='$PIP_ARGS' "
                }
            }
        }
        stage('Publish package') {
            when {
                buildingTag()
            }
            steps {
                script {
                    withCredentials([string(credentialsId: 'nexus_username', variable: 'NEXUS_USERNAME'), string(credentialsId: 'nexus_password', variable: 'NEXUS_PASSWORD')]) {
                        runInPrefectContainer("""
                            python setup.py sdist bdist_wheel --new-version ${BUILD_CONFIG_NAME}
                            twine upload dist/* --repository-url ${PYPI_URL} -u ${NEXUS_USERNAME} -p ${NEXUS_PASSWORD} --non-interactive
                        """)
                                    
                    }
                }

            }
        }
        stage('Blocks: Register prefect block types') {
            when {
                buildingTag()
            }
            steps {
                script {
                    def blocks = readYaml file: '.openshift/blocks.yaml'
                    for (block in blocks.blocks) {
                        runInPrefectContainer("prefect blocks register -f ${block.path}")
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                if (env.BRANCH_NAME.startsWith('PR')) {
                    setGitHubBuildStatus('Build', 'SUCCESS')
                }
            }
        }
        failure {
            script {
                if (env.BRANCH_NAME.startsWith('PR')) {
                    setGitHubBuildStatus('Build', 'FAILURE')
                }
            }
        }
        always {
            jiraSendBuildInfo site: "${JIRA_URL}"
            // Archive test results
            script {
                sh "docker image prune -af"
                if (fileExists('./tests/test_results.xml')) {
                    junit 'tests/test_results.xml'
                } else {
                    echo 'No test results found'
                }
            }
        }
    }
}

void setGitHubBuildStatus(String message, String state) {
    step([
        $class: 'GitHubCommitStatusSetter',
        reposSource: [$class: 'ManuallyEnteredRepositorySource', url: "${GIT_URL}"],
        commitShaSource: [$class: 'ManuallyEnteredShaSource', sha: "${GIT_COMMIT}"],
        errorHandlers: [[$class: 'ChangingBuildStatusErrorHandler', result: 'UNSTABLE']],
        statusResultSource: [ $class: 'ConditionalStatusResultSource', results: [[$class: 'AnyBuildResult', message: message, state: state]] ]
    ])
}
void getPrefectApiAndVersion(String deploy_env) {
    env.DEPLOYMENT_ENV = deploy_env
    switch (deploy_env) {
        case 'int':
            env.PREFECT_API_URL = "${PREFECT_URL_V3_TST}"
            break
        case 'qas':
            env.PREFECT_API_URL = "${PREFECT_URL_QAS}"
            break
        case 'prd':
            env.PREFECT_API_URL = "${PREFECT_URL_PRD}"
            break
        default:
            break
    }
    def response = sh(returnStdout: true, script:"curl $PREFECT_API_URL/admin/version").trim().split('"')
    env.PREFECT_VERSION = response[1]
}
void runInPrefectContainer(String commands) {
    println("$commands")
    docker.image("prefect-meemoo:$GIT_SHORT_COMMIT").inside {
        sh """#!/bin/bash
        set -e
        $commands
        """
    }
}
